# Site settings
title: My Jekyll Site
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my Jekyll website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://axs6.github.io/repo" # the base hostname & protocol for your site
twitter_username: your_twitter
github_username:  your_github

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files or directories from processing
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock

# Include additional directories or files for processing
include:
  - _pages

# Permalinks settings
permalink: /:year/:month/:day/:title:output_ext

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Jekyll Feed settings
feed:
  path: feed.xml

# Jekyll SEO Tag settings
seo:
  title: My Jekyll Site
  description: "A description of your site."
  author: "Your Name"
  twitter: "your_twitter"
  url: "https://axs6.github.io/repo"
